baseURL = 'https://AkihiroTakamura.github.io/tech-blog'
languageCode = 'ja'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'ゆるふわブログ'
theme = 'mainroad'

[params]
  text_color = 'dark-gray'
  background_color_class = 'bg-navy'
  author = 'Akihiro Takamura'
  favicon = '/images/profile.png'
  site_logo = '/images/profile.png'

[[params.ananke_socials]]
  name = 'twitter'
  url  = 'https://twitter.com/rinda2001'
