version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

    ports:
      - "1313:1313"

    volumes:
      - ..:/workspace:delegated
      - $HOME$USERPROFILE/.aws:/home/dev/.aws

    tty: true
